### ISSUE TITLE
Automatic data refresh of tabs in VEDA 2.0 after SYNC?

### ISSUE THREAD

**Issue by panosev** [kanors-emr/Veda2.0-Installation#8]
Hi Veda team, 

I was wondering if it is possible after a SYNC of a model to automatic update any open tabs (modules) in VEDA 2.0. For example, if I have opened the "Items Details" module and I SYNC my model because e.g., I have introduced a new UC, if I do not manually refresh the "Items Details" after the SYNC I will not see my newly introduced UC in this tab.  Of course not all modules need automatic data refresh after a SYNC. I think reasonable are the "Browse", "Items List" and "Items Details". 

However, I can well imagine that automatically updating the already opened tabs (modules) after a SYNC could create significant time delays when syncing the model until the VEDA 2.0 is responsive to the user again, if the database is large. Nevertheless, I thought to mention this in case you come up with  a good solution :-)  

Best wishes, 
Vangelis

**Comment by akanudia** [comment]
I have also felt the need for this; I will discuss it with the team.
Meanwhile, note that F5 works as Refresh on all Veda2.0 screens.

**Comment by akanudia** [comment]
So, we discussed this and realized that we have disabled this feature after building. There are several use cases that can result in confusion, or even application errors, because Veda2.0 leaves all input browse modules fully functional during the Sync process. One possibility is to have a checkbox "refresh after Sync" and not allow user activity on Browse and Items View during Sync, if checked. What do you think?

**Comment by panosev** [comment]
I think what your propose makes sense to avoid introducing dysfunctionalities to the application.
